package com.yiqirong.androidbaseframework.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yiqirong.androidbaseframework.database.CrushInfo;

import com.yiqirong.androidbaseframework.database.CrushInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig crushInfoDaoConfig;

    private final CrushInfoDao crushInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        crushInfoDaoConfig = daoConfigMap.get(CrushInfoDao.class).clone();
        crushInfoDaoConfig.initIdentityScope(type);

        crushInfoDao = new CrushInfoDao(crushInfoDaoConfig, this);

        registerDao(CrushInfo.class, crushInfoDao);
    }
    
    public void clear() {
        crushInfoDaoConfig.clearIdentityScope();
    }

    public CrushInfoDao getCrushInfoDao() {
        return crushInfoDao;
    }

}
